# Generated by Django 6.0.4 on 2026-04-22 09:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bouquets', '0002_supply_bouquetsupply_bouquet_supplies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('DELIVERING', 'Доставляется'), ('COMPLETED', 'Завершен'), ('CANCELLED', 'Отменен')], db_index=True, default='NEW', max_length=20, verbose_name='Статус заказа')),
                ('delivery_time', models.CharField(choices=[('ASAP', 'Как можно скорее'), ('10-12', 'с 10:00 до 12:00'), ('12-14', 'с 12:00 до 14:00'), ('14-16', 'с 14:00 до 16:00'), ('16-18', 'с 16:00 до 18:00'), ('18-20', 'с 18:00 до 20:00')], db_index=True, default='ASAP', max_length=20, verbose_name='Время доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bouquet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bouquets.bouquet', verbose_name='Букет')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
