# Generated by Django 6.0.4 on 2026-04-21 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Дополнение',
                'verbose_name_plural': 'Дополнения',
            },
        ),
        migrations.CreateModel(
            name='BouquetSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouquets.bouquet')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouquets.supply', verbose_name='Дополнение')),
            ],
            options={
                'verbose_name': 'Дополнение для букета',
                'verbose_name_plural': 'Дополнения для букета',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='supplies',
            field=models.ManyToManyField(through='bouquets.BouquetSupply', to='bouquets.supply', verbose_name='Дополнения'),
        ),
    ]
