# Generated by Django 6.0.4 on 2026-04-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquets', '0002_supply_bouquetsupply_bouquet_supplies'),
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
                ('category', models.CharField(blank=True, choices=[('event', 'Событие'), ('style', 'Стиль'), ('color', 'Цветовая гамма'), ('budget', 'Бюджет'), ('flower', 'Цветок'), ('other', 'Прочее')], max_length=20, null=True, verbose_name='Категория тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название квиза')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='bouquets.bouquettag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер шага')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='bouquets.quiz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Вопрос квиза',
                'verbose_name_plural': 'Вопросы квиза',
                'ordering': ['quiz', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('tags', models.ManyToManyField(blank=True, to='bouquets.bouquettag', verbose_name='Теги, добавляемые при выборе')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='bouquets.quizquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'step_number'), name='unique_step_per_quiz'),
        ),
    ]
