# Generated by Django 6.0.4 on 2026-04-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bouquets",
            "0003_bouquettag_quiz_bouquet_tags_quizquestion_quizanswer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bouquettag",
            name="max_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Макс. цена",
            ),
        ),
        migrations.AddField(
            model_name="bouquettag",
            name="min_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Мин. цена",
            ),
        ),
    ]
