# Generated by Django 6.0.4 on 2026-04-23 10:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана'), ('cancelled', 'Отменена')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультации',
                'ordering': ['-created_at'],
            },
        ),
    ]
